# Refresh historical hand-written Rd usage/arguments from the actual APIs.
root <- if (file.exists("DESCRIPTION")) "." else "TCGASigSurvival"
env <- new.env(parent = globalenv())
for (path in list.files(file.path(root, "R"), full.names = TRUE)) sys.source(path, env)
descriptions <- c(
  target_gene = "Human target-gene symbol.",
  signature_genes = "Character vector of signature gene symbols.",
  signature_name = "Signature name used in labels and output filenames.",
  project_dir = "Project directory containing input and output folders.",
  data_dir = "Directory containing the public TCGA input files.",
  out_dir = "Directory for result tables and figures.",
  expression_file = "Path to the Xena gene expression matrix.",
  survival_file = "Path to the Pan-Cancer Atlas clinical survival table.",
  phenotype_file = "Path to Xena sample phenotype metadata.",
  gencode_file = "Path to the GENCODE v23 GTF annotation.",
  output_prefix = "Optional basename for generated output files.",
  write_files = "Whether to write tables and QC reports.",
  verbose = "Whether to print progress messages.",
  prepared = "Prepared-data list or path to its saved RDS file.",
  min_signature_genes = "Minimum number of usable signature genes within a cohort.",
  min_patients = "Minimum number of patients for a cohort model.",
  min_events = "Minimum number of OS death events for a cohort model.",
  include_skcm_primary_only = "Include the overlapping SKCM primary-only sensitivity cohort.",
  cutoff_methods = "Median and/or optimized grouping methods. Optimized cutoffs are exploratory.",
  optimized_minprop = "Minimum group fraction in optimized cutoff selection.",
  make_km = "Whether to generate Kaplan-Meier PDFs.",
  make_summary_plots = "Whether to generate forest plots and heatmaps.",
  make_expression_plot = "Whether to generate the target-expression comparison for optimized groups.",
  results = "Survival result table, or a supported result object as described below.",
  results_file = "Path to an existing survival result TSV, used when results is NULL.",
  survival = "Returned survival-analysis list containing result and sample-score tables.",
  survival_input = "Patient-level survival input and score table.",
  survival_input_file = "Path to a patient-level survival input TSV.",
  cutoff_method = "Grouping method to display, median or optimized.",
  signature_sets = "Named list of gene-symbol vectors for multiple signatures.",
  proteogenomics_dir = "Directory containing separately generated CPTAC workflow outputs.",
  include_joint_tables = "Whether to load patient-level CPTAC joint tables.",
  fdr_cutoff = "BH false-discovery-rate threshold used for summaries.",
  rerun = "Whether to execute the external CPTAC workflow before reading its outputs.",
  runner = "Path to an externally supplied CPTAC shell runner; not bundled with this package.",
  runner_args = "Arguments passed to the external shell runner.",
  width = "Figure width in inches.",
  height = "Figure height in inches.",
  dpi = "PNG resolution in dots per inch."
  , default_only = "Whether to display only default cohorts, excluding sensitivity cohorts."
  , delta_height = "Height in inches for the mean-expression difference figure."
  , boxplot_width = "Width in inches for the target-expression boxplot."
  , boxplot_height = "Height in inches for the target-expression boxplot."
)
for (path in list.files(file.path(root, "man"), pattern = "[.]Rd$", full.names = TRUE)) {
  lines <- readLines(path)
  if (any(grepl("Generated by roxygen2", head(lines, 3), fixed = TRUE))) next
  rd <- tools::parse_Rd(path)
  tags <- vapply(rd, function(x) attr(x, "Rd_tag"), character(1))
  aliases <- vapply(rd[tags == "\\alias"], function(x) trimws(paste(unlist(x), collapse = "")), character(1))
  functions <- aliases[vapply(aliases, function(x) is.function(env[[x]]), logical(1))]
  if (!length(functions)) next
  usage <- unlist(lapply(functions, function(name) {
    text <- deparse(args(env[[name]]), width.cutoff = 90L)
    text <- text[text != "NULL"]
    text[1] <- sub("^function ", name, text[1])
    text[length(text)] <- sub("[[:space:]]*NULL$", "", text[length(text)])
    c(text, "")
  }))
  parameters <- unique(unlist(lapply(functions, function(name) names(formals(env[[name]])))))
  missing <- setdiff(parameters, names(descriptions))
  if (length(missing)) stop("Missing parameter descriptions: ", paste(missing, collapse = ", "))
  arguments <- if (length(parameters)) c("\\arguments{", vapply(parameters, function(name)
    paste0("\\item{", name, "}{", descriptions[[name]], "}"), character(1)), "}") else character()
  replace <- which(tags %in% c("\\usage", "\\arguments"))
  for (index in rev(replace)) {
    ref <- as.integer(attr(rd[[index]], "srcref"))
    lines <- c(if (ref[1] > 1) lines[seq_len(ref[1] - 1L)],
      if (tags[index] == "\\usage") c("\\usage{", usage, "}") else arguments,
      if (ref[3] < length(lines)) lines[seq.int(ref[3] + 1L, length(lines))])
  }
  if (!"\\arguments" %in% tags) lines <- c(lines, arguments)
  writeLines(lines, path)
}
